#ifndef VALLY_ECS_ECS_COMPONENTS_H_
#define VALLY_ECS_ECS_COMPONENTS_H_

#include <vally/config.h>

typedef i32 entity;

typedef enum {
  ECS_ALIVE = BIT_MASK(0),
  ECS_TRANSFORM_COMPONENT = BIT_MASK(1),
  ECS_SPRITERENDERER_COMPONENT = BIT_MASK(2),
  ECS_RIGIDBODY_COMPONENT = BIT_MASK(3),
  ECS_ANIMATOR_COMPONENT = BIT_MASK(4),
} component_mask;

#endif // !VALLY_ECS_ECS_COMPONENTS_H_